version: "3.8"
services:
  app: # 서비스 이름
    container_name: app_server
    image: ojeegu/second-hand-04-a #cicd.yml에서 설정한 이미지 이름 (변수?)
    ports:
      - 8080:8080

  nginx: # 서비스 이름
    container_name: proxy_server
    image: nginx:latest # 최신 버전
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 호스트 경로:컨테이너 경로 연결
      - ./data/certbot/data:/var/www/certbot:ro
      - ./data/cerbot/conf:/etc/nginx/ssl:ro
    depends_on:
      - app # app 서비스가 실행되어야 nginx 서비스가 실행

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email myemail@google.com --agree-tos --no-eff-email -d fishprincess.site
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/logs:/var/log/letsencrypt:rw
      - ./data/certbot/data:/var/www/certbot:rw

volumes:
  shared-data: #로컬 또는 서버에 생성되는 폴더 (컨테이너 폴더와 연결)
