version: "3.8"
services:
  app: # 서비스 이름
    container_name: app_server
    image: ojeegu/second-hand-04-a #cicd.yml에서 설정한 이미지 이름 (변수?)
    ports:
      - 8080:8080

  nginx: # 서비스 이름
    container_name: proxy_server
    image: nginx:latest # 최신 버전
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 호스트 경로:컨테이너 경로 연결
      - ./data/cerbot/conf:/etc/letsencrypt
      - ./data/cerbot/www:/var/www/cerbot
    depends_on:
      - app # app 서비스가 실행되어야 nginx 서비스가 실행
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \\"daemon off;\\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  shared-data: #로컬 또는 서버에 생성되는 폴더 (컨테이너 폴더와 연결)
