version: "3.8"
services:
  app: # 서비스 이름
    container_name: app_server
    image: ojeegu/second-hand-04-a #cicd.yml에서 설정한 이미지 이름 (변수?)
    ports:
      - 8080:8080

  nginx: # 서비스 이름
    container_name: proxy_server
    image: nginx:latest # 최신 버전
    ports:
      - '80:80'
    #      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # 호스트 경로:컨테이너 경로 연결
    depends_on:
      - app # app 서비스가 실행되어야 nginx 서비스가 실행

volumes:
  shared-data: #로컬 또는 서버에 생성되는 폴더 (컨테이너 폴더와 연결)
